[default]
auto_detect_solc = true
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_difficulty = 0
block_number = 1
block_timestamp = 1
bytecode_hash = 'none'
cache = true
cache_path = 'cache'
evm_version = 'london'
extra_output = []
extra_output_files = []
ffi = false
force = false
fuzz_max_global_rejects = 65536
fuzz_max_local_rejects = 1492
fuzz_runs = 1024
gas_limit = 9223372036854775807
gas_price = 0
gas_reports = ['*']
ignored_error_codes = [1878]
initial_balance = '0xffffffffffffffffffffffff'
libraries = []
libs = ['lib']
memory_limit = 33554432
names = true
no_storage_caching = false
offline = false
optimizer = true
optimizer_runs = 1_000
out = 'out'
remappings = []
sender = '0xafFEaFFEAFfeAfFEAffeaFfEAfFEaffeafFeAFfE'
sizes = false
sparse_mode = false
src = 'src'
test = 'test'
tx_origin = '0xAaaaAaAAaaaAAaAAaAaaaaAAAAAaAaaaAaAaaAA0'
verbosity = 3
via_ir = true

[default.rpc_storage_caching]
chains = 'all'
endpoints = 'all'

[ci]
optimizer = false
fuzz_runs = 4069
force = true
verbosity = 4
